defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Monisha Jegadeesan
subtitle: 

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Research
    link: /research
    icon: ""

  - text: Curriculum Vitae
    link: /cv.pdf
    icon: ""

  - text: Contact
    link: /contact
    icon: ""

# Socialmedia Icons
social_icons:
  # - name: email
  #   link: https://monishaj@cse.iitm.ac.in
  #   icon: fas fa-envelope-square

  - name: linkedin
    link: https://www.linkedin.com/in/monisha-jegadeesan
    icon: fab fa-linkedin

  - name: twitter
    link: https://twitter.com/monisha_jega
    icon: fab fa-twitter-square

  - name: github
    link: https://github.com/monisha-jega
    icon: fab fa-github-square

  - name: googlescholar
    link: https://scholar.google.com/citations?user=Orp6iLcAAAAJ&hl=en
    icon: fas fa-scroll

  - name: goodreads
    link: https://www.goodreads.com/user/show/28840222-monisha-jegadeesan
    icon: fas fa-book



